//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestDB1Entities : DbContext
    {
        public TestDB1Entities()
            : base("name=TestDB1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_AuthORTrans> Tbl_AuthORTrans { get; set; }
        public virtual DbSet<Tbl_Book> Tbl_Book { get; set; }
        public virtual DbSet<Tbl_BookCategory> Tbl_BookCategory { get; set; }
        public virtual DbSet<Tbl_BookSubCategory> Tbl_BookSubCategory { get; set; }
        public virtual DbSet<Tbl_Cities> Tbl_Cities { get; set; }
        public virtual DbSet<Tbl_Countries> Tbl_Countries { get; set; }
        public virtual DbSet<Tbl_States> Tbl_States { get; set; }
    }
}
