//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Cities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Cities()
        {
            this.Tbl_AuthORTrans = new HashSet<Tbl_AuthORTrans>();
        }
    
        public int ID { get; set; }
        public int StateID { get; set; }
        public string Name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_AuthORTrans> Tbl_AuthORTrans { get; set; }
        public virtual Tbl_States Tbl_States { get; set; }
    }
}
