//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Book
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int AuthORTransID { get; set; }
        public int CategorytID { get; set; }
        public Nullable<int> ISBN { get; set; }
        public Nullable<short> PublishedNumber { get; set; }
        public Nullable<System.DateTime> PublishedDate { get; set; }
        public Nullable<int> PageCount { get; set; }
        public Nullable<short> VolNumber { get; set; }
        public Nullable<short> VolCount { get; set; }
    
        public virtual Tbl_AuthORTrans Tbl_AuthORTrans { get; set; }
        public virtual Tbl_BookSubCategory Tbl_BookSubCategory { get; set; }
    }
}
